### ISSUE TITLE
 Cannot find module 'install-referrer'.`

### ISSUE THREAD

**Issue by ClickerVinod** [DualH/cordova-plugin-installreferrer#2]
Hi,
i have followed step  but getting this error

`[ng] ERROR in src/app/public/home/home.page.ts(13,33): error TS2307: Cannot find module 'install-referrer'.`

http://prntscr.com/nti6ll

```
Ionic:

   ionic (Ionic CLI)             : 4.12.0 (C:\Users\Asus\AppData\Roaming\npm\node_modules\ionic)
   Ionic Framework               : @ionic/angular 4.4.2                                                 allreferrer.git
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1
```

Plz, help how I can test without publish my app on Play Store.

**Comment by DualH** [comment]
Hi @ClickerVinod,

Because @ionic-native doesn't have install-referrer, you must copy the folder from my npm and paste in node_modules/@ionic-native

Regards

**Comment by DualH** [comment]
Check it this
https://github.com/DualH/cordova-plugin-installreferrer/issues/1#issuecomment-477220693
