### ISSUE TITLE
install-referrer not found

### ISSUE THREAD

**Issue by shubhamtakode** [DualH/cordova-plugin-installreferrer#3]
When I'm trying to import using 
import { InstallReferrer } from 'install-referrer';
Its not working.

**Comment by pullatjunaid** [comment]
I have the same error. Any solution ???

**Comment by pullatjunaid** [comment]
I got a solution, 
Just run `npm install install-referrer`
This will work.

Wish you all the best

**Comment by shadrach-tayo** [comment]
@pullatjunaid mine works but during testing it throws the error 'getReferrer is not a function' and I use ionic 4.20.0

**Comment by DualH** [comment]
Hello everybody,

For ionic > 3, u have to use from the next way

``` js 
import { InstallReferrer } from 'install-referrer/ngx';
```

Best regards

**Comment by ravimehta5690** [comment]
I have used the same way you have said getting an error

> Native: tried calling InstallReferrer.getReferrer, but the InstallReferrer plugin is not installed.
> (anonymous)
> Install the InstallReferrer plugin: 'ionic cordova plugin add cordova-plugin-installreferrer'
