### ISSUE TITLE
Error TypeError: Object(...) is not a function for getReferrer().

### ISSUE THREAD

**Issue by Gokulanathan29** [DualH/cordova-plugin-installreferrer#4]
Hi,

 I m using ionic 3 and i installed cordova-plugin-installreferrer and while run android getting

 ERROR Error: Uncaught (in promise): TypeError: Object(...) is not a function
TypeError: Object(...) is not a function` for this._installReferrer.getReferrer().

my import: 
import { InstallReferrer } from 'install-referrer/ngx';

my package.json:

 "cordova-plugin-installreferrer": "^2.0.0",
    "install-referrer": "^5.11.0",
    "ionic-angular": "3.9.9",

**Comment by DualH** [comment]
Hello,

Sorry for the delays in responding, I am currently working on a new version because it is obsolete

Greetings
